version: "3.8"

services:
  journal-app-fullstack-rag:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - journal-app-microservice-rag
    image: ${DOCKER_USERNAME}/journal-app-fullstack-rag:latest

  journal-app-microservice-rag:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: ${DOCKER_USERNAME}/journal-app-microservice-rag:latest

