version: "3.8"

services:
  frontend-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - microservice-rag

  microservice-rag:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

